### ISSUE TITLE
library reference missing?

### ISSUE THREAD

**Issue by vfulco** [rdrr1990/datascience101#1]
The post describing the publication is excellent.  However, it makes passing reference to a "library(docxtrackr)" which I am unable to find doing a google search, within the repo or on CRAN.

Please advise. TIA.

**Comment by rdrr1990** [comment]
Apologies for the typo. See [docxtractr](https://cran.r-project.org/web/packages/docxtractr/docxtractr.pdf). You may also be curious about [WordR](https://rviews.rstudio.com/2017/10/04/wordr---a-new-r-package-for-rendering-documents-in-ms-word-format/) if you haven't already seen it. HTH!
